#!/usr/bin/env python3
"""
Interactive Q&A assistant over the local geotechnical knowledge base.

Plan Week 4, Option A (CLI): type a question, get a source-grounded answer
generated by the local Foundry Local LLM. Fully offline.

Prereqs:
    foundry service start
    foundry model load phi-4-mini --device GPU   # or set LLM_MODEL in .env
    python src/ingest.py                         # build the knowledge base

Usage:
    python src/chat.py
Type 'q', 'quit', 'exit' or 'çık' to leave.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from logging_setup import configure_logging
from rag_pipeline import FoundryError, RAGPipeline

# Absolute so the CLI works from any working directory, not just the repo root.
DB_PATH = os.path.join(os.path.dirname(HERE), "data", "rag.db")

EXIT_WORDS = {"q", "quit", "exit", "çık", "cik", "kapat"}


def main():
    configure_logging()

    print("\n" + "=" * 60)
    print("  GEOTEKNİK SORU-CEVAP ASİSTANI (yerel / offline)")
    print("=" * 60)

    try:
        rag = RAGPipeline(db_path=DB_PATH)  # model from LLM_MODEL in .env
    except FoundryError as error:
        print(f"\nFoundry Local'e bağlanılamadı:\n{error}\n")
        sys.exit(1)

    print("\nSorunu yaz ve Enter'a bas. Çıkmak için: q / çık\n")

    while True:
        try:
            query = input("Soru> ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            break

        if not query:
            continue
        if query.lower() in EXIT_WORDS:
            break

        result = rag.answer(query, top_k=3)

        print("\nCevap:")
        print(result["answer"])

        if result["sources"]:
            print("\nKaynaklar:")
            seen = set()
            for s in result["sources"]:
                key = (s["file"], s["chunk"])
                if key in seen:
                    continue
                seen.add(key)
                print(f"  - {s['file']} (parça {s['chunk']}, "
                      f"benzerlik {s['similarity']:.2f})")
        print("\n" + "-" * 60 + "\n")

    rag.close()
    print("Görüşürüz! 👋")


if __name__ == "__main__":
    main()
